CREATE TABLE score
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration_number VARCHAR(255)                             NOT NULL,
    maths               FLOAT                                    NOT NULL,
    literature          FLOAT                                    NOT NULL,
    language            FLOAT                                    NOT NULL,
    physics             FLOAT,
    chemistry           FLOAT,
    biology             FLOAT,
    history             FLOAT,
    geography           FLOAT,
    gdcd                FLOAT,
    total_a             FLOAT,
    language_code       VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_score PRIMARY KEY (id)
);

ALTER TABLE score
    ADD CONSTRAINT uc_score_registration_number UNIQUE (registration_number);

CREATE INDEX idx_registration_num ON score (registration_number);

CREATE INDEX idx_total_A ON score (total_a);


CREATE TABLE statistic (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mon_hoc VARCHAR(255) NOT NULL,
    group1 INT,
    group2 INT,
    group3 INT,
    group4 INT
);
CREATE INDEX idx_mon_hoc ON statistic (mon_hoc);